#ifndef NOBJ_TML_H
#define NOBJ_TML_H

static const char nobj_tml_data[] =

"template ani_event\n"
"{1247357D-E63F-4316-AB58-E2BA90F06ABC}\n"
"{\n"
"	dword   event_type;\n"
"	dword   event_detail;\n"
"	dword   event_time;\n"
"	string  event_file_name;\n"
"	dword   event_direction;\n"
"	dword   event_property;\n"
"}\n"
"template ani_event_list\n"
"{A77F9538-A44C-42b3-9266-01FDA84E6573}\n"
"{\n"
"	string      ani_name;\n"
"	dword       event_list_size;\n"
"	ani_event	event_list[event_list_size];\n"
"}\n"
"template cob_mesh_part_list\n"
"{2F46F4A1-9DC3-4fb4-8A9F-6EED47DD2A39}\n"
"{\n"
"	dword  mesh_part_num;\n"
"	dword  mesh_part_size;\n"
"	string mesh_part_list[mesh_part_size];\n"
"}\n"
"template cob_header_v10\n"
"{5103BB2E-ECBA-44ad-B67E-C69A3F415C65}\n"
"{\n"
"	dword              obj_partindex;\n"
"	dword              obj_clan;\n"
"	dword              obj_sex;\n"
"	dword              mesh_part_size;\n"
"	cob_mesh_part_list mesh_part_list[mesh_part_size];\n"
"	dword		       ani_list_size;\n"
"	string             ani_list[ani_list_size];\n"
"	dword		       ani_event_size;\n"
"	ani_event_list     ani_event_list[ani_event_size];\n"
"}\n"
"template effect_pos\n"
"{C72669AC-858A-48ea-89CA-2E7BB9D60EE2}\n"
"{\n"
"	dword			nIndex;\n"
"	string			effect_pos_name;\n"
"}\n"
"template lod_data\n"
"{07BD7F6E-1F3B-45a9-BF27-40CAF95132E6}\n"
"{\n"
"	dword			nLevel;\n"
"	string			lod_name;\n"
"}\n"
"template cob_header_v11\n"
"{7AA3937F-5183-40d2-B6AF-CCBDE5C96E55}\n"
"{\n"
"	dword              obj_partindex;\n"
"	dword              obj_clan;\n"
"	dword              obj_sex;\n"
"	dword              render_type;\n"
"	dword              prop_category;\n"
"	dword              shadow_type;\n"
"	float			   sel_cube[6];\n"
"	float			   dead_cube[6];\n"
"	float			   visible_cube[6];\n"
"	float			   collide_cube[6];\n"
"	dword		       effpos_list_size;\n"
"	effect_pos         effpos_list[effpos_list_size];\n"
"	dword		       lod_list_size;\n"
"	lod_data		   lod_list[lod_list_size];\n"
"	string             height_file_name;\n"
"	dword		       mesh_list_size;\n"
"	string             mesh_list[mesh_list_size];\n"
"	dword              mesh_part_size;\n"
"	cob_mesh_part_list mesh_part_list[mesh_part_size];\n"
"	dword		       ani_list_size;\n"
"	string             ani_list[ani_list_size];\n"
"	dword		       ani_event_size;\n"
"	ani_event_list     ani_event_list[ani_event_size];\n"
"}\n"
"template cob_header_v12\n"
"{F1D867AA-07E3-4246-BFB8-6436ED556775}\n"
"{\n"
"	dword              obj_partindex;\n"
"	dword              obj_clan;\n"
"	dword              obj_sex;\n"
"	dword              render_type;\n"
"	dword              prop_category;\n"
"	dword              shadow_type;\n"
"	float			   sel_cube[6];\n"
"	float			   dead_cube[6];\n"
"	float			   visible_cube[6];\n"
"	float			   collide_cube[6];\n"
"	dword		       effpos_list_size;\n"
"	effect_pos         effpos_list[effpos_list_size];\n"
"	dword		       lod_list_size;\n"
"	lod_data		   lod_list[lod_list_size];\n"
"	string             height_file_name;\n"
"	string             camera_collision_file_name;\n"
"	dword		       mesh_list_size;\n"
"	string             mesh_list[mesh_list_size];\n"
"	dword              mesh_part_size;\n"
"	cob_mesh_part_list mesh_part_list[mesh_part_size];\n"
"	dword		       ani_list_size;\n"
"	string             ani_list[ani_list_size];\n"
"	dword		       ani_event_size;\n"
"	ani_event_list     ani_event_list[ani_event_size];\n"
"}\n"
"template seq_texture_data\n"
"{85937876-8EB1-8C81-973B-47EA41F87B73}\n"
"{\n"
"	dword				texture_name_list_size;\n"
"	string				texture_name_list[texture_name_list_size];\n"
"}\n"
"template seq_data\n"
"{A369B9C5-6AD2-3043-516A-A34714BB3145}\n"
"{\n"
"	string				str_seq_name;\n"
"	dword				texture_group_size;\n"
"	seq_texture_data	seq_texture_list[texture_group_size];\n"
"}\n"
"template nx3_seq_data\n"
"{B452EB91-77E7-A8E2-B519-5DCB38DB3A67}\n"
"{\n"
"	string		str_nx3_name;\n"
"	dword		ani_part_index;\n"
"	dword		seq_size;\n"
"	seq_data	seq_list[seq_size];\n"
"}\n"
"template mesh_texture_data\n"
"{3B73E288-2CD5-77D0-799F-B37E77BB5D99}\n"
"{\n"
"	dword				nx3_size;\n"
"	nx3_seq_data		nx3_seq_list[nx3_size];\n"
"}\n"
"template cob_header_v13\n"
"{72E978BB-18F4-5357-D7C9-7547FE667886}\n"
"{\n"
"	dword              obj_partindex;\n"
"	dword              obj_clan;\n"
"	dword              obj_sex;\n"
"	dword              render_type;\n"
"	dword              prop_category;\n"
"	dword              shadow_type;\n"
"	float			   sel_cube[6];\n"
"	float			   dead_cube[6];\n"
"	float			   visible_cube[6];\n"
"	float			   collide_cube[6];\n"
"	dword		       effpos_list_size;\n"
"	effect_pos         effpos_list[effpos_list_size];\n"
"	dword		       lod_list_size;\n"
"	lod_data		   lod_list[lod_list_size];\n"
"	string             height_file_name;\n"
"	string             camera_collision_file_name;\n"
"	dword		       mesh_list_size;\n"
"	string             mesh_list[mesh_list_size];\n"
"	dword              mesh_part_size;\n"
"	cob_mesh_part_list mesh_part_list[mesh_part_size];\n"
"	dword		       ani_list_size;\n"
"	string             ani_list[ani_list_size];\n"
"	dword		       ani_event_size;\n"
"	ani_event_list     ani_event_list[ani_event_size];\n"
"	dword				mesh_texture_size;\n"
"	mesh_texture_data	mesh_texture_list[mesh_texture_size];\n"
"}\n"
;

#endif
