#ifndef NX3_TML_H
#define NX3_TML_H

static const char nx3_tml_data[] =

"template nx3_version_header\n"
"{81BCE021-AD76-346f-9C7D-19885FD118B6}\n"
"{\n"
"	dword	version;\n"
"}\n"
"template nx3_mtl_block\n"
"{81BCE071-AC76-496f-9C7D-19885FD118B6}\n"
"{\n"
"	string  mtl_name;\n"
"	string	texture_name;\n"
"	dword	mtl_id;\n"
"	dword	channel_id;\n"
"	float	power;\n"
"	float	self_illumi;\n"
"	char	smoothing;\n"
"	dword	ambient;\n"
"	dword	diffuse;\n"
"	dword	specular;\n"
"}\n"
"template nx3_mtl\n"
"{52BCCAA6-3C16-4286-8B9E-1A798F9D94DE}\n"
"{\n"
"	dword			sub_mtl_block_size;\n"
"	nx3_mtl_block	sub_mtl_block_array[sub_mtl_block_size];\n"
"}\n"
"template nx3_mtl_header\n"
"{209BBB41-681F-4b9b-9744-4D88E1413DCC}\n"
"{\n"
"	dword	mtl_size;\n"
"	nx3_mtl	mtl_array[mtl_size];\n"
"}\n"
"template old_nx3_mesh_frame\n"
"{CB3441E8-5740-4c6e-84AC-455C3AC08DCA}\n"
"{\n"
"	dword   time_value;\n"
"	dword	vertex_size;\n"
"	float	vertex_array[vertex_size];\n"
"	dword	normal_size;\n"
"	float	normal_array[normal_size];\n"
"	dword	texel_size;\n"
"	float	texel_array[texel_size];\n"
"	dword	color_size;\n"
"	dword	color_array[color_size];\n"
"}\n"
"template nx3_weight_frame\n"
"{B513DF30-80BE-44f4-980B-84B9D979A607}\n"
"{\n"
"	string  bone_name;\n"
"	dword	weight_size;\n"
"	float	weight_array[weight_size];\n"
"	dword	offset_vector_size;\n"
"	float   offset_vector_array[offset_vector_size];\n"
"}\n"
"template nx3_mesh_frame\n"
"{1C77954B-CDD5-4615-B7AD-F23BD3D0C23E}\n"
"{\n"
"	dword   time_value;\n"
"	dword	vertex_size;\n"
"	float	vertex_array[vertex_size];\n"
"	dword	normal_size;\n"
"	float	normal_array[normal_size];\n"
"	dword	texel_size;\n"
"	float	texel_array[texel_size];\n"
"	dword	color_size;\n"
"	dword	color_array[color_size];\n"
"	dword				bone_size;\n"
"	nx3_weight_frame	bone_block[bone_size];\n"
"	float	mesh_tm[16];\n"
"}\n"
"template nx3_mesh_block\n"
"{C817F7B0-E4E7-40fb-97B3-2B97CC000521}\n"
"{\n"
"	dword			texture_index;\n"
"	dword			mesh_frame_size;\n"
"	nx3_mesh_frame	mesh_frame_array[mesh_frame_size];\n"
"	dword			index_buffer_size;\n"
"	word			index_buffer_array[index_buffer_size];\n"
"	dword			lightmap_index;\n"
"}\n"
"template nx3_ani_block\n"
"{630E91D8-A032-47c1-89F3-2BD5938B336E}\n"
"{\n"
"	dword	time;\n"
"	float	matrix[12];\n"
"}\n"
"template nx3_visi_block\n"
"{AA9BA163-BCD9-4eb8-831A-0B656C304995}\n"
"{\n"
"	dword		time;\n"
"	float		visibility;\n"
"}\n"
"template nx3_fx_block\n"
"{83A78B40-C401-451d-8AE2-D26BEAB73E5A}\n"
"{\n"
"	dword		time;\n"
"	string		note;\n"
"}\n"
"template nx3_fx\n"
"{22C5CCD2-C9FC-4aa8-A63A-6677296313F8}\n"
"{\n"
"	dword			fx_block_size;\n"
"	nx3_fx_block	fx_block_array[fx_block_size];\n"
"}\n"
"template nx3_mesh\n"
"{0748DC1A-1DB1-458a-9C7E-B3D46FC4585B}\n"
"{\n"
"	string			mesh_name;\n"
"	dword			material_id;\n"
"	dword			channel_id;\n"
"	dword			mesh_block_size;\n"
"	nx3_mesh_block	mesh_block_array[mesh_block_size];\n"
"	dword			ani_block_size;\n"
"	nx3_ani_block	ani_block_array[ani_block_size];\n"
"	dword			visi_block_size;\n"
"	nx3_visi_block	visi_block_array[visi_block_size];\n"
"	dword			fx_size;\n"
"	nx3_fx			fx_array[fx_size];\n"
"	dword			mesh_children_size;\n"
"	nx3_mesh        mesh_children_array[mesh_children_size];\n"
"}\n"
"template nx3_new_mesh\n"
"{1718DC1B-1DB1-458a-9C7E-C3D46FC4585B}\n"
"{\n"
"	string			mesh_name;\n"
"	dword			material_id;\n"
"	dword			channel_id;\n"
"	dword			mesh_block_size;\n"
"	nx3_mesh_block	mesh_block_array[mesh_block_size];\n"
"	dword			ani_time_size;\n"
"	dword			ani_time_array[ani_time_size];\n"
"	dword			ani_matrix_size;\n"
"	float			ani_matrix_array[ani_matrix_size];\n"
"	dword			visi_time_size;\n"
"	dword			visi_time_array[visi_time_size];\n"
"	float			visi_value_array[visi_time_size];\n"
"	dword			fx_size;\n"
"	nx3_fx			fx_array[fx_size];\n"
"	dword			mesh_children_size;\n"
"	nx3_new_mesh    mesh_children_array[mesh_children_size];\n"
"}\n"
"template nx3_mesh_tm\n"
"{F09C560E-7328-411e-87A3-EEB165D5F929}\n"
"{\n"
"	string		name;\n"
"	float       tm[16];\n"
"}\n"
"template old_nx3_mesh_header\n"
"{D3699024-DB2C-4855-9CB5-FAA4F1CE20D7}\n"
"{\n"
"	dword		mesh_size;\n"
"	nx3_mesh    mesh_array[mesh_size];\n"
"}\n"
"template nx3_mesh_header\n"
"{D6D25AEB-A735-4fef-A17D-6E2117498226}\n"
"{\n"
"	dword		mesh_size;\n"
"	nx3_mesh    mesh_array[mesh_size];\n"
"	dword		mesh_tm_size;\n"
"	nx3_mesh_tm mesh_tm_array[mesh_tm_size];\n"
"}\n"
"template nx3_new_mesh_header\n"
"{A6D25AEB-A735-1fef-C17D-EE2117498226}\n"
"{\n"
"	dword			mesh_size;\n"
"	nx3_new_mesh    mesh_array[mesh_size];\n"
"	dword			mesh_tm_size;\n"
"	nx3_mesh_tm		mesh_tm_array[mesh_tm_size];\n"
"}\n"
"template nx3_camera_block\n"
"{3D80819B-0CB9-4da4-9773-4C23198FEB7F}\n"
"{\n"
"	float	mat_object[12];\n"
"	float	mat_target[12];\n"
"	char	has_target;\n"
"	dword	time_value;\n"
"	float	fov;\n"
"	float	dist;\n"
"	float	hither;\n"
"	float	yon;\n"
"	float	near_range;\n"
"	float	far_range;\n"
"}\n"
"template nx3_camera\n"
"{55E7B200-BE6C-4719-85E4-DBB4F31654FD}\n"
"{\n"
"	string				block_name;\n"
"	dword				camera_block_size;\n"
"	nx3_camera_block	camera_block_array[camera_block_size];\n"
"}\n"
"template nx3_light_block\n"
"{2542DF01-5429-4ae0-8F3E-3A0EC0841DB2}\n"
"{\n"
"	float	mat_object[12];\n"
"	float	mat_target[12];\n"
"	dword	time_value;\n"
"	dword	clr_light;\n"
"	float	intens;\n"
"	float	atten_start;\n"
"	float	atten_end;\n"
"	char	onoff;\n"
"}\n"
"template nx3_light\n"
"{690414EE-85A9-40d3-892B-58596A6A20C4}\n"
"{\n"
"	string			block_name;\n"
"	dword			light_type;\n"
"	dword			ambient_light;\n"
"	dword			light_block_size;\n"
"	nx3_light_block	light_block_array[light_block_size];\n"
"}\n"
"template nx3_light_header\n"
"{445E49A8-A0F9-4a30-9BF2-4D7FC575B87D}\n"
"{\n"
"	dword		light_size;\n"
"	nx3_light	light_array[light_size];\n"
"}\n"
"template nx3_bone_ani\n"
"{B84344DE-A1B6-4aa7-AFD6-22CA8A4B0CEE}\n"
"{\n"
"	string  szName;\n"
"	dword	parent_Index;\n"
"	float	base_tm[16];\n"
"	dword	flag;\n"
"	dword   pos_time_size;\n"
"	dword   pos_time_array[pos_time_size];\n"
"	dword	pos_key_size;\n"
"	float	pos_key_array[pos_key_size];\n"
"	dword   rot_time_size;\n"
"	dword   rot_time_array[rot_time_size];\n"
"	dword	rot_key_size;\n"
"	float	rot_key_array[rot_key_size];\n"
"	dword	child_size;\n"
"	dword	child_Index_array[child_size];\n"
"}\n"
"template nx3_bone_ani_channel\n"
"{81B3C137-B2B8-40b0-A3AD-D149467F5932}\n"
"{\n"
"	string  channel_name;\n"
"	dword	channel_flag;\n"
"	dword   channel_time_span;\n"
"	dword   channel_frame_rate;\n"
"	dword		 bone_ani_size;\n"
"	nx3_bone_ani bone_ani_array[bone_ani_size];\n"
"}\n"
"template nx3_bone_ani_header\n"
"{E8F9296B-B9DD-4080-8BC7-6C69E0AA3FEB}\n"
"{\n"
"	dword bone_count;\n"
"	dword channel_count;\n"
"	nx3_bone_ani_channel channel_array[channel_count];\n"
"}\n"
"template test_string\n"
"{40BA1DFC-1E0B-49ee-8EDB-91C3952CDD56}\n"
"{\n"
"	string data\n"
"}\n"
;

#endif
